### ISSUE TITLE
Samples in READMEs for openai and anthropic plugins are swapped

### ISSUE THREAD

**Issue by pavelgj** [Dabolus/genkit-plugins#1]
https://github.com/Dabolus/genkit-plugins/blob/main/plugins/anthropic/README.md -- has GPT4 sample
https://github.com/Dabolus/genkit-plugins/blob/main/plugins/openai/README.md -- has anthropic sample

**Comment by Dabolus** [comment]
Thanks for noticing! Fixed in commit 86be71a6292fa371b6aa5279f5533413f3f11e48 and released in version `0.2.0`
